---
title: "Syllabus"
output:
  html_document:
    toc: yes
    toc_depth: 1
    toc_float:
      collapsed: no
---

<style>
h1{font-weight: 400;}
</style>


# Basic Course Information {#basicinfo}

* **Course title:** SDS 192: Introduction to Data Science
* **Instructor:** [Albert Y. Kim](https://rudeboybert.rbind.io/){target="_blank"} - Assistant Professor of Statistical & Data Sciences
* **Data assistants**: From the [Spinelli Center for Quantitative Learning (QLC)](https://www.smith.edu/qlc/){target="_blank"}
    + Jordan Moody on Monday + Wednesday
    + Paige Patrick on Friday
    + Zixian Li
* **~~Email:~~ Slack team**: Click hashtag icon in navbar for the browser interface or use the [desktop app](https://slack.com/downloads/){target="_blank"}.
* **Lectures:** Sec 01: MWF 11:00-12:10 - McConnell 103
* **Outside help**:
    + M & Tu 3-6pm or by appointment - McConnell Hall 215
    + From the Spinelli Center for Quantitative Learning (QLC)
        1. [Tutoring](https://www.smith.edu/qlc/tutoring.html?colStats=open#PanelStats){target="_blank"}: Sunday thru Thursday 7-9pm - McConnell Hall 301.
        1. [Data Counselor Raul Zelada Aprili](https://www.smith.edu/qlc/tutoring.html?colDataCnslr=open#PanelDataCnslr){target="_blank"}: By appointment - Spinelli Center.
  
## Expectations

* **Slack**:
    + You are expected to stay on top of announcements and
direct messages in Slack. For strategies that suit you and your work style (ex: turning on email notifications), please don't hesistate to ask me for suggestions!
    + I will respond to Slack messages within 24h, but will respond to weekend messages (Friday afternoon to Monday morning) at my discretion.
    + If possible, please only Slack me with briefer and administrative questions; I prefer having more substantive conversations in person. 
* **Lectures**:
    + You do not need to inform me of *occasional* absenses.
However, you are responsible for asking your peers for what you missed. For
example, makeup lectures will not be held during office hours.
    + You are expected to bring your fully charged laptop, a set of headphones, colored pens/pencils, and your paper notebook to every lecture.



*** 


    
# Course Description & Objectives

* **Official course description**: On [Smith College
Course Search](https://www.smith.edu/academics/academic-program/curriculum/course-search?term=Fall+2018&dept=Statistical+and+Data+Sciences&instr=Albert+Y.+Kim&credits=&course_numb=192&course_keywd=&op=Submit&form_build_id=form-7cQWYLnNXxPrKj_HYG_M0FCUgwmOR_VZguPCdiDJOZU&form_id=campus_course_search_basic_search_form){target="_blank"}.
* **Objectives**: This semester you will
    1. Take your first steps into the world of data.
    1. For those new to programming, learn just enough coding and computational thinking to work with data. For those with some experience programming, start expanding your "data science toolbox."
    1. Dip your toes into the world of open-source software and start engaging with the open-source community.
    1. Tell your first "data stories" via projects.



***



# Topic Schedule and Readings

A rough topic schedule and corresponding readings are posted below and on the [main](index.html) page. We will draw from the following sources:

1. ["ModernDive: An Introduction to Statistical and Data Sciences via R (MD)"](https://moderndive.netlify.com/){target="_blank"} by Ismay and Kim (link in menubar above).
1. ["Modern Data Science with R (MDSR)"](https://mdsr-book.github.io/){target="_blank"} by Baumer, Kaplan, and Horton.
1. ["Text Mining with R (TMR)"](https://www.tidytextmining.com/){target="_blank"} by Silge and Robinson.
1. [DataCamp](https://www.datacamp.com/enterprise/2018-09-sds192-intro-to-data-science/assignments){target="_blank"}: an online interactive environment for learning data science currently via R and Python. On top of the DataCamp courses we'll cover this semester, you have free access to [all their courses](https://www.datacamp.com/courses/all){target="_blank"} for 6 months. 

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vRvggFhESyu_EFxrcFQXsZtdaQqaqcQ6kgWg173WTkTeWV67RWiZ01G8jhJsQ2b5VUVCJqQ8xo6COWM/pubhtml?gid=1373353942&single=true&amp;widget=true&amp;headers=false" width="100%" height="300"></iframe>

## Expectations

* **Topics**: Note the topic schedule may shift depending on class progress. That being said, I will try to keep the schedule up-to-date for at least the upcoming two lectures.
* **Readings**:
    + You are not required to cover readings for any given lecture beforehand as you'll be given class time to do so in the presence of your peers. However, if you feel you would benefit from reading beforehand, please feel free!
    + You are however responsible for finishing the readings before the start of the next lecture.
* **Reference**: These are optional reference readings if you would like a second perspective on the readings. For example, say you would like a second persepective on "scatterplots" on top of what we covered in ModernDive, I suggest reading any sections related to "scatterplots" in MDSR Chapter 3 as needed, not the entire chapter.
* **DataCamp**: You do not need to cover the listed courses beforehand; they will be assigned as lab work (see [Quizzes and Labs](#labs) below).
* **Important Events**: Please be sure to frequently check the far-right column for important deadlines and events.


    
***



# Evaluation

## Problem Sets 30%

Problem sets will involve computational assignments with written explanations. All homework must be submitted electronically before midnight of the due date. While no late submissions will be accepted, the lowest two problem set scores will be dropped in the final problem set grade.

More details coming soon.

## Quizzes and Labs 20% {#labs}

This course will include quizzes and lab sessions. Advance notice will be given for all quizzes. The labs will be conducted primarily in R and/or DataCamp, with some supplemental exercises in other platforms at the my discretion. Students are strongly encouraged to work in groups during these labs. 

## Projects 40%

You will work on 4-5 group projects (exact number TBD) over the course of the semester. These projects will be structured, but fairly open-ended to allow you be creative. Evaluation will emphasize originality and ingenuity in addition to sophistication and complexity.

## Engagement 10% {#engagement}

It is difficult to explicit codify what constitutes "an engaged student," so 
instead I present the following rough principle I will follow: *you'll only get
out of this class as much as you put in*. Some examples of behavior counter to
this principle:

* Not participating in class.
* Engaging so little with me, either in class or during office hours, that I
don't know what your voice sounds like.
* Shirking group work.
* [Ghosting](https://www.urbandictionary.com/define.php?term=Ghosting&utm_source=search-action){target="_blank"}.
* Doing the bare minimum to get by. 

## Expectations {#evaluation-expectations}

* **DataCamp**:
    1. DataCamp is meant to be low stakes-practice, so the only thing that matters for your grade is whether you complete the course. So while things like the number of hints/solutions taken don't factor into your grade, it is important to make a good faith effort to answer these questions the best you can.
    1. Taking notes based on what you cover is not required, but please do so if you feel you will benefit. 
    1. You should be taking no more than roughly 4 hours per DataCamp assignment.
    1. Please note retention of the material will not be perfect the first time through. The only way to really retain the material is via lots of practice/doing. For now, think of this as a introduction.
    1. You do not need to complete any DataCamp courses in preparation for future lectures; they will always be explicitly assigned and you will subsequently be given time during Tu/Th lab sections to do them. 
1. **Collaboration**: While I encourage you to work with your peers for problem
sets and labs, you must submit your own answers and not simple rewordings of
another's work. Furthermore, all collaborations must be explicitly acknowledged
in your submissions.
1. **Honor Code**: All your work must follow the [Smith College Academic Honor
Code
Statement](https://www.smith.edu/sao/handbook/socialconduct/honorcode.php){target="_blank"};
in particular all external sources must be cited in your submissions.



***



# Accommodations
 
Smith is committed to providing support services and reasonable accommodations
to all students with disabilities. To request an accommodation, please register
with the Disability Services Office at the beginning of the semester. To do so,
call 413.585.2071 to arrange an appointment with Laura Rauscher, Director of
Disability Services.

## Expectations

If you require accommodations, please provide me with documentation
and advance notice for when you think you will need them.



*** 



# Code of Conduct

As the instructor and assistants for this course, we are committed to making
participation in this course a harassment-free experience for everyone,
regardless of level of experience, gender, gender identity and expression,
sexual orientation, disability, personal appearance, body size, race, ethnicity,
age, or religion. Examples of unacceptable behavior by participants in this
course include the use of sexual language or imagery, derogatory comments or
personal attacks, trolling, public or private harassment, insults, or other
unprofessional conduct.

As the instructor and assistants we have the right and responsibility to point
out and stop behavior that is not aligned to this Code of Conduct. Participants
who do not follow the Code of Conduct may be reprimanded for such behavior.
Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the instructor.

This Code of Conduct is adapted from the [Contributor
Covenant](http://contributor-covenant.org){target="_blank"}, version 1.0.0,
available [here](http://contributor-covenant.org/version/1/0/0/){target="_blank"}.

## Expectations

All students, the instructor, and all assistants are expected to adhere to this
Code of Conduct in all settings: lectures, office hours, during tutoring hours,
and over Slack.
